/*
 * API
 * Matching Engine Web Rules API
 *
 * OpenAPI spec version: v1
 * Contact: support@spanishpoint.ie
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.example.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * SpanishPointCoreBDOEntitiesWorkPerformer
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-04T19:50:41.548694176+02:00[Europe/Madrid]")

public class SpanishPointCoreBDOEntitiesWorkPerformer {
  @SerializedName("lastName")
  private String lastName = null;

  @SerializedName("firstName")
  private String firstName = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("personID")
  private Long personID = null;

  public SpanishPointCoreBDOEntitiesWorkPerformer lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  @Schema(description = "")
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public SpanishPointCoreBDOEntitiesWorkPerformer firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/
  @Schema(description = "")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public SpanishPointCoreBDOEntitiesWorkPerformer name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public SpanishPointCoreBDOEntitiesWorkPerformer type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(description = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public SpanishPointCoreBDOEntitiesWorkPerformer personID(Long personID) {
    this.personID = personID;
    return this;
  }

   /**
   * Get personID
   * @return personID
  **/
  @Schema(description = "")
  public Long getPersonID() {
    return personID;
  }

  public void setPersonID(Long personID) {
    this.personID = personID;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SpanishPointCoreBDOEntitiesWorkPerformer spanishPointCoreBDOEntitiesWorkPerformer = (SpanishPointCoreBDOEntitiesWorkPerformer) o;
    return Objects.equals(this.lastName, spanishPointCoreBDOEntitiesWorkPerformer.lastName) &&
        Objects.equals(this.firstName, spanishPointCoreBDOEntitiesWorkPerformer.firstName) &&
        Objects.equals(this.name, spanishPointCoreBDOEntitiesWorkPerformer.name) &&
        Objects.equals(this.type, spanishPointCoreBDOEntitiesWorkPerformer.type) &&
        Objects.equals(this.personID, spanishPointCoreBDOEntitiesWorkPerformer.personID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lastName, firstName, name, type, personID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SpanishPointCoreBDOEntitiesWorkPerformer {\n");
    
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    personID: ").append(toIndentedString(personID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
