/*
 * API
 * Matching Engine Web Rules API
 *
 * OpenAPI spec version: v1
 * Contact: support@spanishpoint.ie
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.example.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets SpanishPoint.Core.BDO.Entities.Work.ContributorRole
 */
@JsonAdapter(SpanishPointCoreBDOEntitiesWorkContributorRole.Adapter.class)
public enum SpanishPointCoreBDOEntitiesWorkContributorRole {
  @SerializedName("CA")
  CA("CA"),
  @SerializedName("AR")
  AR("AR"),
  @SerializedName("SE")
  SE("SE"),
  @SerializedName("PA")
  PA("PA"),
  @SerializedName("ES")
  ES("ES"),
  @SerializedName("AM")
  AM("AM"),
  @SerializedName("SA")
  SA("SA"),
  @SerializedName("C")
  C("C"),
  @SerializedName("AD")
  AD("AD"),
  @SerializedName("A")
  A("A"),
  @SerializedName("E")
  E("E"),
  @SerializedName("AQ")
  AQ("AQ"),
  @SerializedName("SR")
  SR("SR"),
  @SerializedName("TR")
  TR("TR"),
  @SerializedName("MO")
  MO("MO"),
  @SerializedName("OP")
  OP("OP"),
  @SerializedName("PR")
  PR("PR"),
  @SerializedName("X")
  X("X");

  private String value;

  SpanishPointCoreBDOEntitiesWorkContributorRole(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static SpanishPointCoreBDOEntitiesWorkContributorRole fromValue(String input) {
    for (SpanishPointCoreBDOEntitiesWorkContributorRole b : SpanishPointCoreBDOEntitiesWorkContributorRole.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<SpanishPointCoreBDOEntitiesWorkContributorRole> {
    @Override
    public void write(final JsonWriter jsonWriter, final SpanishPointCoreBDOEntitiesWorkContributorRole enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public SpanishPointCoreBDOEntitiesWorkContributorRole read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return SpanishPointCoreBDOEntitiesWorkContributorRole.fromValue((String)(value));
    }
  }
}
