/*
 * API
 * Matching Engine Web Rules API
 *
 * OpenAPI spec version: v1
 * Contact: support@spanishpoint.ie
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.example.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
/**
 * SpanishPointCoreBDOEntitiesWorkWorkSourceIP
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-04T19:50:41.548694176+02:00[Europe/Madrid]")

public class SpanishPointCoreBDOEntitiesWorkWorkSourceIP {
  @SerializedName("workSourceIPID")
  private Long workSourceIPID = null;

  @SerializedName("ipiNameNumber")
  private Long ipiNameNumber = null;

  @SerializedName("fullName")
  private String fullName = null;

  @SerializedName("workID")
  private Long workID = null;

  @SerializedName("lastModifiedDate")
  private String lastModifiedDate = null;

  public SpanishPointCoreBDOEntitiesWorkWorkSourceIP workSourceIPID(Long workSourceIPID) {
    this.workSourceIPID = workSourceIPID;
    return this;
  }

   /**
   * Get workSourceIPID
   * @return workSourceIPID
  **/
  @Schema(description = "")
  public Long getWorkSourceIPID() {
    return workSourceIPID;
  }

  public void setWorkSourceIPID(Long workSourceIPID) {
    this.workSourceIPID = workSourceIPID;
  }

  public SpanishPointCoreBDOEntitiesWorkWorkSourceIP ipiNameNumber(Long ipiNameNumber) {
    this.ipiNameNumber = ipiNameNumber;
    return this;
  }

   /**
   * Get ipiNameNumber
   * @return ipiNameNumber
  **/
  @Schema(description = "")
  public Long getIpiNameNumber() {
    return ipiNameNumber;
  }

  public void setIpiNameNumber(Long ipiNameNumber) {
    this.ipiNameNumber = ipiNameNumber;
  }

  public SpanishPointCoreBDOEntitiesWorkWorkSourceIP fullName(String fullName) {
    this.fullName = fullName;
    return this;
  }

   /**
   * Get fullName
   * @return fullName
  **/
  @Schema(description = "")
  public String getFullName() {
    return fullName;
  }

  public void setFullName(String fullName) {
    this.fullName = fullName;
  }

  public SpanishPointCoreBDOEntitiesWorkWorkSourceIP workID(Long workID) {
    this.workID = workID;
    return this;
  }

   /**
   * Get workID
   * @return workID
  **/
  @Schema(description = "")
  public Long getWorkID() {
    return workID;
  }

  public void setWorkID(Long workID) {
    this.workID = workID;
  }

  public SpanishPointCoreBDOEntitiesWorkWorkSourceIP lastModifiedDate(String lastModifiedDate) {
    this.lastModifiedDate = lastModifiedDate;
    return this;
  }

   /**
   * Get lastModifiedDate
   * @return lastModifiedDate
  **/
  @Schema(description = "")
  public String getLastModifiedDate() {
    return lastModifiedDate;
  }

  public void setLastModifiedDate(String lastModifiedDate) {
    this.lastModifiedDate = lastModifiedDate;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SpanishPointCoreBDOEntitiesWorkWorkSourceIP spanishPointCoreBDOEntitiesWorkWorkSourceIP = (SpanishPointCoreBDOEntitiesWorkWorkSourceIP) o;
    return Objects.equals(this.workSourceIPID, spanishPointCoreBDOEntitiesWorkWorkSourceIP.workSourceIPID) &&
        Objects.equals(this.ipiNameNumber, spanishPointCoreBDOEntitiesWorkWorkSourceIP.ipiNameNumber) &&
        Objects.equals(this.fullName, spanishPointCoreBDOEntitiesWorkWorkSourceIP.fullName) &&
        Objects.equals(this.workID, spanishPointCoreBDOEntitiesWorkWorkSourceIP.workID) &&
        Objects.equals(this.lastModifiedDate, spanishPointCoreBDOEntitiesWorkWorkSourceIP.lastModifiedDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(workSourceIPID, ipiNameNumber, fullName, workID, lastModifiedDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SpanishPointCoreBDOEntitiesWorkWorkSourceIP {\n");
    
    sb.append("    workSourceIPID: ").append(toIndentedString(workSourceIPID)).append("\n");
    sb.append("    ipiNameNumber: ").append(toIndentedString(ipiNameNumber)).append("\n");
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("    workID: ").append(toIndentedString(workID)).append("\n");
    sb.append("    lastModifiedDate: ").append(toIndentedString(lastModifiedDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
