/*
 * API
 * Matching Engine Web Rules API
 *
 * OpenAPI spec version: v1
 * Contact: support@spanishpoint.ie
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.example.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * SpanishPointCoreBDOEntitiesWorkWorkContributor
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-04T19:50:41.548694176+02:00[Europe/Madrid]")

public class SpanishPointCoreBDOEntitiesWorkWorkContributor {
  @SerializedName("workContributorID")
  private Long workContributorID = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("lastName")
  private String lastName = null;

  @SerializedName("ipiNumber")
  private Long ipiNumber = null;

  @SerializedName("ipiBaseNumber")
  private String ipiBaseNumber = null;

  @SerializedName("typeCode")
  private String typeCode = null;

  @SerializedName("role")
  private String role = null;

  @SerializedName("mechanicalShare")
  private Double mechanicalShare = null;

  @SerializedName("performingShare")
  private Double performingShare = null;

  @SerializedName("subTypeId")
  private Integer subTypeId = null;

  @SerializedName("writerPublisherShare")
  private Double writerPublisherShare = null;

  @SerializedName("roleId")
  private Integer roleId = null;

  @SerializedName("roleCode")
  private String roleCode = null;

  @SerializedName("isWriter")
  private Boolean isWriter = null;

  @SerializedName("setType")
  private String setType = null;

  @SerializedName("setTypeGroup")
  private String setTypeGroup = null;

  @SerializedName("senderRep")
  private Boolean senderRep = null;

  @SerializedName("sourceIP")
  private Long sourceIP = null;

  @SerializedName("sourceType")
  private String sourceType = null;

  @SerializedName("sourceSociety")
  private String sourceSociety = null;

  @SerializedName("relationships")
  private String relationships = null;

  @SerializedName("analysisCode")
  private String analysisCode = null;

  @SerializedName("accountNumber")
  private String accountNumber = null;

  @SerializedName("idOriginal")
  private String idOriginal = null;

  @SerializedName("isPublicDomain")
  private Boolean isPublicDomain = null;

  public SpanishPointCoreBDOEntitiesWorkWorkContributor workContributorID(Long workContributorID) {
    this.workContributorID = workContributorID;
    return this;
  }

   /**
   * Get workContributorID
   * @return workContributorID
  **/
  @Schema(description = "")
  public Long getWorkContributorID() {
    return workContributorID;
  }

  public void setWorkContributorID(Long workContributorID) {
    this.workContributorID = workContributorID;
  }

  public SpanishPointCoreBDOEntitiesWorkWorkContributor name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public SpanishPointCoreBDOEntitiesWorkWorkContributor lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  @Schema(description = "")
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public SpanishPointCoreBDOEntitiesWorkWorkContributor ipiNumber(Long ipiNumber) {
    this.ipiNumber = ipiNumber;
    return this;
  }

   /**
   * Get ipiNumber
   * @return ipiNumber
  **/
  @Schema(description = "")
  public Long getIpiNumber() {
    return ipiNumber;
  }

  public void setIpiNumber(Long ipiNumber) {
    this.ipiNumber = ipiNumber;
  }

  public SpanishPointCoreBDOEntitiesWorkWorkContributor ipiBaseNumber(String ipiBaseNumber) {
    this.ipiBaseNumber = ipiBaseNumber;
    return this;
  }

   /**
   * Get ipiBaseNumber
   * @return ipiBaseNumber
  **/
  @Schema(description = "")
  public String getIpiBaseNumber() {
    return ipiBaseNumber;
  }

  public void setIpiBaseNumber(String ipiBaseNumber) {
    this.ipiBaseNumber = ipiBaseNumber;
  }

  public String typeCode(String typeCode) {
    this.typeCode = typeCode;
    return this.typeCode;
  }

   /**
   * Get typeCode
   * @return typeCode
  **/
  @Schema(description = "")
  public String getTypeCode() {
    return typeCode;
  }

  public void setTypeCode(String typeCode) {
    this.typeCode = typeCode;
  }

  public String role(String role) {
    this.role = role;
    return this.role;
  }

   /**
   * Get role
   * @return role
  **/
  @Schema(description = "")
  public String getRole() {
    return role;
  }

  public void setRole(String role) {
    this.role = role;
  }

  public SpanishPointCoreBDOEntitiesWorkWorkContributor mechanicalShare(Double mechanicalShare) {
    this.mechanicalShare = mechanicalShare;
    return this;
  }

   /**
   * Get mechanicalShare
   * @return mechanicalShare
  **/
  @Schema(description = "")
  public Double getMechanicalShare() {
    return mechanicalShare;
  }

  public void setMechanicalShare(Double mechanicalShare) {
    this.mechanicalShare = mechanicalShare;
  }

  public SpanishPointCoreBDOEntitiesWorkWorkContributor performingShare(Double performingShare) {
    this.performingShare = performingShare;
    return this;
  }

   /**
   * Get performingShare
   * @return performingShare
  **/
  @Schema(description = "")
  public Double getPerformingShare() {
    return performingShare;
  }

  public void setPerformingShare(Double performingShare) {
    this.performingShare = performingShare;
  }

  public SpanishPointCoreBDOEntitiesWorkWorkContributor subTypeId(Integer subTypeId) {
    this.subTypeId = subTypeId;
    return this;
  }

   /**
   * Get subTypeId
   * @return subTypeId
  **/
  @Schema(description = "")
  public Integer getSubTypeId() {
    return subTypeId;
  }

  public void setSubTypeId(Integer subTypeId) {
    this.subTypeId = subTypeId;
  }

  public SpanishPointCoreBDOEntitiesWorkWorkContributor writerPublisherShare(Double writerPublisherShare) {
    this.writerPublisherShare = writerPublisherShare;
    return this;
  }

   /**
   * Get writerPublisherShare
   * @return writerPublisherShare
  **/
  @Schema(description = "")
  public Double getWriterPublisherShare() {
    return writerPublisherShare;
  }

  public void setWriterPublisherShare(Double writerPublisherShare) {
    this.writerPublisherShare = writerPublisherShare;
  }

  public SpanishPointCoreBDOEntitiesWorkWorkContributor roleId(Integer roleId) {
    this.roleId = roleId;
    return this;
  }

   /**
   * Get roleId
   * @return roleId
  **/
  @Schema(description = "")
  public Integer getRoleId() {
    return roleId;
  }

  public void setRoleId(Integer roleId) {
    this.roleId = roleId;
  }

  public SpanishPointCoreBDOEntitiesWorkWorkContributor roleCode(String roleCode) {
    this.roleCode = roleCode;
    return this;
  }

   /**
   * Get roleCode
   * @return roleCode
  **/
  @Schema(description = "")
  public String getRoleCode() {
    return roleCode;
  }

  public void setRoleCode(String roleCode) {
    this.roleCode = roleCode;
  }

  public SpanishPointCoreBDOEntitiesWorkWorkContributor isWriter(Boolean isWriter) {
    this.isWriter = isWriter;
    return this;
  }

   /**
   * Get isWriter
   * @return isWriter
  **/
  @Schema(description = "")
  public Boolean isIsWriter() {
    return isWriter;
  }

  public void setIsWriter(Boolean isWriter) {
    this.isWriter = isWriter;
  }

  public SpanishPointCoreBDOEntitiesWorkWorkContributor setType(String setType) {
    this.setType = setType;
    return this;
  }

   /**
   * Get setType
   * @return setType
  **/
  @Schema(description = "")
  public String getSetType() {
    return setType;
  }

  public void setSetType(String setType) {
    this.setType = setType;
  }

  public SpanishPointCoreBDOEntitiesWorkWorkContributor setTypeGroup(String setTypeGroup) {
    this.setTypeGroup = setTypeGroup;
    return this;
  }

   /**
   * Get setTypeGroup
   * @return setTypeGroup
  **/
  @Schema(description = "")
  public String getSetTypeGroup() {
    return setTypeGroup;
  }

  public void setSetTypeGroup(String setTypeGroup) {
    this.setTypeGroup = setTypeGroup;
  }

  public SpanishPointCoreBDOEntitiesWorkWorkContributor senderRep(Boolean senderRep) {
    this.senderRep = senderRep;
    return this;
  }

   /**
   * Get senderRep
   * @return senderRep
  **/
  @Schema(description = "")
  public Boolean isSenderRep() {
    return senderRep;
  }

  public void setSenderRep(Boolean senderRep) {
    this.senderRep = senderRep;
  }

  public SpanishPointCoreBDOEntitiesWorkWorkContributor sourceIP(Long sourceIP) {
    this.sourceIP = sourceIP;
    return this;
  }

   /**
   * Get sourceIP
   * @return sourceIP
  **/
  @Schema(description = "")
  public Long getSourceIP() {
    return sourceIP;
  }

  public void setSourceIP(Long sourceIP) {
    this.sourceIP = sourceIP;
  }

  public SpanishPointCoreBDOEntitiesWorkWorkContributor sourceType(String sourceType) {
    this.sourceType = sourceType;
    return this;
  }

   /**
   * Get sourceType
   * @return sourceType
  **/
  @Schema(description = "")
  public String getSourceType() {
    return sourceType;
  }

  public void setSourceType(String sourceType) {
    this.sourceType = sourceType;
  }

  public SpanishPointCoreBDOEntitiesWorkWorkContributor sourceSociety(String sourceSociety) {
    this.sourceSociety = sourceSociety;
    return this;
  }

   /**
   * Get sourceSociety
   * @return sourceSociety
  **/
  @Schema(description = "")
  public String getSourceSociety() {
    return sourceSociety;
  }

  public void setSourceSociety(String sourceSociety) {
    this.sourceSociety = sourceSociety;
  }

  public SpanishPointCoreBDOEntitiesWorkWorkContributor relationships(String relationships) {
    this.relationships = relationships;
    return this;
  }

   /**
   * Get relationships
   * @return relationships
  **/
  @Schema(description = "")
  public String getRelationships() {
    return relationships;
  }

  public void setRelationships(String relationships) {
    this.relationships = relationships;
  }

  public SpanishPointCoreBDOEntitiesWorkWorkContributor analysisCode(String analysisCode) {
    this.analysisCode = analysisCode;
    return this;
  }

   /**
   * Get analysisCode
   * @return analysisCode
  **/
  @Schema(description = "")
  public String getAnalysisCode() {
    return analysisCode;
  }

  public void setAnalysisCode(String analysisCode) {
    this.analysisCode = analysisCode;
  }

  public SpanishPointCoreBDOEntitiesWorkWorkContributor accountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
    return this;
  }

   /**
   * Get accountNumber
   * @return accountNumber
  **/
  @Schema(description = "")
  public String getAccountNumber() {
    return accountNumber;
  }

  public void setAccountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
  }

  public SpanishPointCoreBDOEntitiesWorkWorkContributor idOriginal(String idOriginal) {
    this.idOriginal = idOriginal;
    return this;
  }

   /**
   * Get idOriginal
   * @return idOriginal
  **/
  @Schema(description = "")
  public String getIdOriginal() {
    return idOriginal;
  }

  public void setIdOriginal(String idOriginal) {
    this.idOriginal = idOriginal;
  }

  public SpanishPointCoreBDOEntitiesWorkWorkContributor isPublicDomain(Boolean isPublicDomain) {
    this.isPublicDomain = isPublicDomain;
    return this;
  }

   /**
   * Get isPublicDomain
   * @return isPublicDomain
  **/
  @Schema(description = "")
  public Boolean isIsPublicDomain() {
    return isPublicDomain;
  }

  public void setIsPublicDomain(Boolean isPublicDomain) {
    this.isPublicDomain = isPublicDomain;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SpanishPointCoreBDOEntitiesWorkWorkContributor spanishPointCoreBDOEntitiesWorkWorkContributor = (SpanishPointCoreBDOEntitiesWorkWorkContributor) o;
    return Objects.equals(this.workContributorID, spanishPointCoreBDOEntitiesWorkWorkContributor.workContributorID) &&
        Objects.equals(this.name, spanishPointCoreBDOEntitiesWorkWorkContributor.name) &&
        Objects.equals(this.lastName, spanishPointCoreBDOEntitiesWorkWorkContributor.lastName) &&
        Objects.equals(this.ipiNumber, spanishPointCoreBDOEntitiesWorkWorkContributor.ipiNumber) &&
        Objects.equals(this.ipiBaseNumber, spanishPointCoreBDOEntitiesWorkWorkContributor.ipiBaseNumber) &&
        Objects.equals(this.typeCode, spanishPointCoreBDOEntitiesWorkWorkContributor.typeCode) &&
        Objects.equals(this.role, spanishPointCoreBDOEntitiesWorkWorkContributor.role) &&
        Objects.equals(this.mechanicalShare, spanishPointCoreBDOEntitiesWorkWorkContributor.mechanicalShare) &&
        Objects.equals(this.performingShare, spanishPointCoreBDOEntitiesWorkWorkContributor.performingShare) &&
        Objects.equals(this.subTypeId, spanishPointCoreBDOEntitiesWorkWorkContributor.subTypeId) &&
        Objects.equals(this.writerPublisherShare, spanishPointCoreBDOEntitiesWorkWorkContributor.writerPublisherShare) &&
        Objects.equals(this.roleId, spanishPointCoreBDOEntitiesWorkWorkContributor.roleId) &&
        Objects.equals(this.roleCode, spanishPointCoreBDOEntitiesWorkWorkContributor.roleCode) &&
        Objects.equals(this.isWriter, spanishPointCoreBDOEntitiesWorkWorkContributor.isWriter) &&
        Objects.equals(this.setType, spanishPointCoreBDOEntitiesWorkWorkContributor.setType) &&
        Objects.equals(this.setTypeGroup, spanishPointCoreBDOEntitiesWorkWorkContributor.setTypeGroup) &&
        Objects.equals(this.senderRep, spanishPointCoreBDOEntitiesWorkWorkContributor.senderRep) &&
        Objects.equals(this.sourceIP, spanishPointCoreBDOEntitiesWorkWorkContributor.sourceIP) &&
        Objects.equals(this.sourceType, spanishPointCoreBDOEntitiesWorkWorkContributor.sourceType) &&
        Objects.equals(this.sourceSociety, spanishPointCoreBDOEntitiesWorkWorkContributor.sourceSociety) &&
        Objects.equals(this.relationships, spanishPointCoreBDOEntitiesWorkWorkContributor.relationships) &&
        Objects.equals(this.analysisCode, spanishPointCoreBDOEntitiesWorkWorkContributor.analysisCode) &&
        Objects.equals(this.accountNumber, spanishPointCoreBDOEntitiesWorkWorkContributor.accountNumber) &&
        Objects.equals(this.idOriginal, spanishPointCoreBDOEntitiesWorkWorkContributor.idOriginal) &&
        Objects.equals(this.isPublicDomain, spanishPointCoreBDOEntitiesWorkWorkContributor.isPublicDomain);
  }

  @Override
  public int hashCode() {
    return Objects.hash(workContributorID, name, lastName, ipiNumber, ipiBaseNumber, typeCode, role, mechanicalShare, performingShare, subTypeId, writerPublisherShare, roleId, roleCode, isWriter, setType, setTypeGroup, senderRep, sourceIP, sourceType, sourceSociety, relationships, analysisCode, accountNumber, idOriginal, isPublicDomain);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SpanishPointCoreBDOEntitiesWorkWorkContributor {\n");
    
    sb.append("    workContributorID: ").append(toIndentedString(workContributorID)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    ipiNumber: ").append(toIndentedString(ipiNumber)).append("\n");
    sb.append("    ipiBaseNumber: ").append(toIndentedString(ipiBaseNumber)).append("\n");
    sb.append("    typeCode: ").append(toIndentedString(typeCode)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    mechanicalShare: ").append(toIndentedString(mechanicalShare)).append("\n");
    sb.append("    performingShare: ").append(toIndentedString(performingShare)).append("\n");
    sb.append("    subTypeId: ").append(toIndentedString(subTypeId)).append("\n");
    sb.append("    writerPublisherShare: ").append(toIndentedString(writerPublisherShare)).append("\n");
    sb.append("    roleId: ").append(toIndentedString(roleId)).append("\n");
    sb.append("    roleCode: ").append(toIndentedString(roleCode)).append("\n");
    sb.append("    isWriter: ").append(toIndentedString(isWriter)).append("\n");
    sb.append("    setType: ").append(toIndentedString(setType)).append("\n");
    sb.append("    setTypeGroup: ").append(toIndentedString(setTypeGroup)).append("\n");
    sb.append("    senderRep: ").append(toIndentedString(senderRep)).append("\n");
    sb.append("    sourceIP: ").append(toIndentedString(sourceIP)).append("\n");
    sb.append("    sourceType: ").append(toIndentedString(sourceType)).append("\n");
    sb.append("    sourceSociety: ").append(toIndentedString(sourceSociety)).append("\n");
    sb.append("    relationships: ").append(toIndentedString(relationships)).append("\n");
    sb.append("    analysisCode: ").append(toIndentedString(analysisCode)).append("\n");
    sb.append("    accountNumber: ").append(toIndentedString(accountNumber)).append("\n");
    sb.append("    idOriginal: ").append(toIndentedString(idOriginal)).append("\n");
    sb.append("    isPublicDomain: ").append(toIndentedString(isPublicDomain)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
