/*
 * API
 * Matching Engine Web Rules API
 *
 * OpenAPI spec version: v1
 * Contact: support@spanishpoint.ie
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.example.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets SpanishPoint.Core.BDO.Enums.ContributorType
 */
@JsonAdapter(SpanishPointCoreBDOEnumsContributorType.Adapter.class)
public enum SpanishPointCoreBDOEnumsContributorType {
  @SerializedName("Publisher")
  PUBLISHER("Publisher"),
  @SerializedName("Writer")
  WRITER("Writer");

  private String value;

  SpanishPointCoreBDOEnumsContributorType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static SpanishPointCoreBDOEnumsContributorType fromValue(String input) {
    for (SpanishPointCoreBDOEnumsContributorType b : SpanishPointCoreBDOEnumsContributorType.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<SpanishPointCoreBDOEnumsContributorType> {
    @Override
    public void write(final JsonWriter jsonWriter, final SpanishPointCoreBDOEnumsContributorType enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public SpanishPointCoreBDOEnumsContributorType read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return SpanishPointCoreBDOEnumsContributorType.fromValue((String)(value));
    }
  }
}
