/*
 * API
 * Matching Engine Web Rules API
 *
 * OpenAPI spec version: v1
 * Contact: support@spanishpoint.ie
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.example.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * SpanishPointCoreBDOEntitiesWorkWorkInstrumentation
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-04T19:50:41.548694176+02:00[Europe/Madrid]")

public class SpanishPointCoreBDOEntitiesWorkWorkInstrumentation {
  @SerializedName("instrumentationCode")
  private String instrumentationCode = null;

  @SerializedName("workInstrumentationID")
  private Long workInstrumentationID = null;

  public SpanishPointCoreBDOEntitiesWorkWorkInstrumentation instrumentationCode(String instrumentationCode) {
    this.instrumentationCode = instrumentationCode;
    return this;
  }

   /**
   * Get instrumentationCode
   * @return instrumentationCode
  **/
  @Schema(description = "")
  public String getInstrumentationCode() {
    return instrumentationCode;
  }

  public void setInstrumentationCode(String instrumentationCode) {
    this.instrumentationCode = instrumentationCode;
  }

  public SpanishPointCoreBDOEntitiesWorkWorkInstrumentation workInstrumentationID(Long workInstrumentationID) {
    this.workInstrumentationID = workInstrumentationID;
    return this;
  }

   /**
   * Get workInstrumentationID
   * @return workInstrumentationID
  **/
  @Schema(description = "")
  public Long getWorkInstrumentationID() {
    return workInstrumentationID;
  }

  public void setWorkInstrumentationID(Long workInstrumentationID) {
    this.workInstrumentationID = workInstrumentationID;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SpanishPointCoreBDOEntitiesWorkWorkInstrumentation spanishPointCoreBDOEntitiesWorkWorkInstrumentation = (SpanishPointCoreBDOEntitiesWorkWorkInstrumentation) o;
    return Objects.equals(this.instrumentationCode, spanishPointCoreBDOEntitiesWorkWorkInstrumentation.instrumentationCode) &&
        Objects.equals(this.workInstrumentationID, spanishPointCoreBDOEntitiesWorkWorkInstrumentation.workInstrumentationID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(instrumentationCode, workInstrumentationID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SpanishPointCoreBDOEntitiesWorkWorkInstrumentation {\n");
    
    sb.append("    instrumentationCode: ").append(toIndentedString(instrumentationCode)).append("\n");
    sb.append("    workInstrumentationID: ").append(toIndentedString(workInstrumentationID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
