/*
 * API
 * Matching Engine Web Rules API
 *
 * OpenAPI spec version: v1
 * Contact: support@spanishpoint.ie
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.example.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * SpanishPointCoreBDOEntitiesWorkName
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-04T19:50:41.548694176+02:00[Europe/Madrid]")

public class SpanishPointCoreBDOEntitiesWorkName {
  @SerializedName("title")
  private String title = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("language")
  private String language = null;

  @SerializedName("titleID")
  private Long titleID = null;

  public SpanishPointCoreBDOEntitiesWorkName title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @Schema(description = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public SpanishPointCoreBDOEntitiesWorkName type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(description = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public SpanishPointCoreBDOEntitiesWorkName language(String language) {
    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  @Schema(description = "")
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public SpanishPointCoreBDOEntitiesWorkName titleID(Long titleID) {
    this.titleID = titleID;
    return this;
  }

   /**
   * Get titleID
   * @return titleID
  **/
  @Schema(description = "")
  public Long getTitleID() {
    return titleID;
  }

  public void setTitleID(Long titleID) {
    this.titleID = titleID;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SpanishPointCoreBDOEntitiesWorkName spanishPointCoreBDOEntitiesWorkName = (SpanishPointCoreBDOEntitiesWorkName) o;
    return Objects.equals(this.title, spanishPointCoreBDOEntitiesWorkName.title) &&
        Objects.equals(this.type, spanishPointCoreBDOEntitiesWorkName.type) &&
        Objects.equals(this.language, spanishPointCoreBDOEntitiesWorkName.language) &&
        Objects.equals(this.titleID, spanishPointCoreBDOEntitiesWorkName.titleID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, type, language, titleID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SpanishPointCoreBDOEntitiesWorkName {\n");
    
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    titleID: ").append(toIndentedString(titleID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
