/*
 * API
 * Matching Engine Web Rules API
 *
 * OpenAPI spec version: v1
 * Contact: support@spanishpoint.ie
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.example.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * SpanishPointCoreBDOEntitiesWorkWorkNumber
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-04T19:50:41.548694176+02:00[Europe/Madrid]")

public class SpanishPointCoreBDOEntitiesWorkWorkNumber {
  @SerializedName("number")
  private String number = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("workNumberID")
  private Long workNumberID = null;

  public SpanishPointCoreBDOEntitiesWorkWorkNumber number(String number) {
    this.number = number;
    return this;
  }

   /**
   * Get number
   * @return number
  **/
  @Schema(description = "")
  public String getNumber() {
    return number;
  }

  public void setNumber(String number) {
    this.number = number;
  }

  public SpanishPointCoreBDOEntitiesWorkWorkNumber type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(description = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public SpanishPointCoreBDOEntitiesWorkWorkNumber workNumberID(Long workNumberID) {
    this.workNumberID = workNumberID;
    return this;
  }

   /**
   * Get workNumberID
   * @return workNumberID
  **/
  @Schema(description = "")
  public Long getWorkNumberID() {
    return workNumberID;
  }

  public void setWorkNumberID(Long workNumberID) {
    this.workNumberID = workNumberID;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SpanishPointCoreBDOEntitiesWorkWorkNumber spanishPointCoreBDOEntitiesWorkWorkNumber = (SpanishPointCoreBDOEntitiesWorkWorkNumber) o;
    return Objects.equals(this.number, spanishPointCoreBDOEntitiesWorkWorkNumber.number) &&
        Objects.equals(this.type, spanishPointCoreBDOEntitiesWorkWorkNumber.type) &&
        Objects.equals(this.workNumberID, spanishPointCoreBDOEntitiesWorkWorkNumber.workNumberID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(number, type, workNumberID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SpanishPointCoreBDOEntitiesWorkWorkNumber {\n");
    
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    workNumberID: ").append(toIndentedString(workNumberID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
