/*
 * API
 * Matching Engine Web Rules API
 *
 * OpenAPI spec version: v1
 * Contact: support@spanishpoint.ie
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.example.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * SpanishPointCoreBDOEntitiesWorkWorkNote
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-04T19:50:41.548694176+02:00[Europe/Madrid]")

public class SpanishPointCoreBDOEntitiesWorkWorkNote {
  @SerializedName("userID")
  private Integer userID = null;

  @SerializedName("noteText")
  private String noteText = null;

  @SerializedName("subject")
  private String subject = null;

  public SpanishPointCoreBDOEntitiesWorkWorkNote userID(Integer userID) {
    this.userID = userID;
    return this;
  }

   /**
   * Get userID
   * @return userID
  **/
  @Schema(description = "")
  public Integer getUserID() {
    return userID;
  }

  public void setUserID(Integer userID) {
    this.userID = userID;
  }

  public SpanishPointCoreBDOEntitiesWorkWorkNote noteText(String noteText) {
    this.noteText = noteText;
    return this;
  }

   /**
   * Get noteText
   * @return noteText
  **/
  @Schema(description = "")
  public String getNoteText() {
    return noteText;
  }

  public void setNoteText(String noteText) {
    this.noteText = noteText;
  }

  public SpanishPointCoreBDOEntitiesWorkWorkNote subject(String subject) {
    this.subject = subject;
    return this;
  }

   /**
   * Get subject
   * @return subject
  **/
  @Schema(description = "")
  public String getSubject() {
    return subject;
  }

  public void setSubject(String subject) {
    this.subject = subject;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SpanishPointCoreBDOEntitiesWorkWorkNote spanishPointCoreBDOEntitiesWorkWorkNote = (SpanishPointCoreBDOEntitiesWorkWorkNote) o;
    return Objects.equals(this.userID, spanishPointCoreBDOEntitiesWorkWorkNote.userID) &&
        Objects.equals(this.noteText, spanishPointCoreBDOEntitiesWorkWorkNote.noteText) &&
        Objects.equals(this.subject, spanishPointCoreBDOEntitiesWorkWorkNote.subject);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userID, noteText, subject);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SpanishPointCoreBDOEntitiesWorkWorkNote {\n");
    
    sb.append("    userID: ").append(toIndentedString(userID)).append("\n");
    sb.append("    noteText: ").append(toIndentedString(noteText)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
